using namespace System.ComponentModel.DataAnnotations.Schema
using namespace System.Reflection
using namespace System.Threading

<#
.SYNOPSIS
	The nullability context.
#>
$NullabilityContext = [ThreadLocal[NullabilityInfoContext]]::new([Func[NullabilityInfoContext]] { [NullabilityInfoContext]::new() })

<#
.SYNOPSIS
	Provides information about a database column.
#>
class ColumnInfo {

	<#
	.SYNOPSIS
		Value indicating whether the column can be read.
	#>
	[bool] $CanRead

	<#
	.SYNOPSIS
		Value indicating whether the column can be written to.
	#>
	[bool] $CanWrite

	<#
	.SYNOPSIS
		Value indicating whether the column value is generated by the database.
	#>
	[bool] $IsComputed

	<#
	.SYNOPSIS
		Value indicating whether the column value is generated by the database when a row is inserted.
	#>
	[bool] $IsIdentity

	<#
	.SYNOPSIS
		Value indicating whether the column value is nullable.
	#>
	[bool] $IsNullable

	<#
	.SYNOPSIS
		The column name.
	#>
	[string] $Name

	<#
	.SYNOPSIS
		The type of the column value.
	#>
	[Type] $Type

	<#
	.SYNOPSIS
		The property information providing the column metadata.
	#>
	hidden [PropertyInfo] $Property

	<#
	.SYNOPSIS
		Creates new column information.
	.PARAMETER Property
		The property information providing the column metadata.
	#>
	ColumnInfo([PropertyInfo] $Property) {
		$this.Property = $Property

		$databaseGeneratedOption = [CustomAttributeExtensions]::GetCustomAttribute[DatabaseGeneratedAttribute]($Property)?.DatabaseGeneratedOption ?? [DatabaseGeneratedOption]::None
		$this.CanRead = $Property.CanRead
		$this.CanWrite = $Property.CanWrite
		$this.IsComputed = $databaseGeneratedOption -ne [DatabaseGeneratedOption]::None
		$this.IsIdentity = $databaseGeneratedOption -eq [DatabaseGeneratedOption]::Identity
		$this.Name = [CustomAttributeExtensions]::GetCustomAttribute[ColumnAttribute]($Property)?.Name ?? $Property.Name
		$this.Type = $Property.PropertyType

		$this.IsNullable = ($null -ne [Nullable]::GetUnderlyingType($Property.PropertyType)) `
			-or ($Script:NullabilityContext.Value.Create($Property).WriteState -ne [NullabilityState]::NotNull)
	}

	<#
	.SYNOPSIS
		Gets the property value of a specified object.
	.PARAMETER Instance
		The object whose property value will be returned.
	.OUTPUTS
		The property value of the specified object.
	#>
	[object] GetValue([object] $Instance) {
		return $this.Property.GetValue($Instance)
	}

	<#
	.SYNOPSIS
		Sets the property value of a specified object.
	.PARAMETER Instance
		The object whose property value will be set.
	.PARAMETER Value
		The new property value.
	#>
	[void] SetValue([object] $Instance, [object] $Value) {
		$this.Property.SetValue($Instance, $Value)
	}
}
