<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>Cedric-Belin.fr</Company>
		<Copyright>© Cédric Belin</Copyright>
		<Description>A simple micro-ORM, based on ADO.NET and data annotations.</Description>
		<Product>SQL Mapper for PowerShell</Product>
		<Version>4.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Belin.Sql.PowerShell</AssemblyName>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NoWarn>FS0044</NoWarn>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Belin.Sql</RootNamespace>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="$(RootNamespace).Tests" />
		<PackageReference Update="FSharp.Core" Version="10.1.401" />
		<PackageReference Include="Belin.Sql" Version="5.3.0" />
		<PackageReference Include="System.Data.Odbc" Version="10.0.12" />
		<PackageReference Include="System.Data.OleDb" Version="10.0.12" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
		<PackageReference Include="System.Management.Automation" Version="7.6.6" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="Command.fs" />
		<Compile Include="Connection.fs" />
		<Compile Include="Mapping.fs" />
		<Compile Include="Object.fs" />
		<Compile Include="Query.fs" />
		<Compile Include="Transaction.fs" />
	</ItemGroup>
</Project>
