namespace Belin.Sql.Reflection;

using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection;

/// <summary>
/// Provides information about a database column.
/// </summary>
/// <param name="propertyInfo">The property information providing the column metadata.</param>
public sealed class ColumnInfo(PropertyInfo propertyInfo) {

	/// <summary>
	/// The nullability context.
	/// </summary>
	private static readonly NullabilityInfoContext nullabilityContext = new();

	/// <summary>
	/// Value indicating whether the column can be read.
	/// </summary>
	public bool CanRead => propertyInfo.CanRead;

	/// <summary>
	/// Value indicating whether the column can be written to.
	/// </summary>
	public bool CanWrite => propertyInfo.CanWrite;

	/// <summary>
	/// Value indicating whether the column value is generated by the database.
	/// </summary>
	public bool IsComputed => databaseGenerated != DatabaseGeneratedOption.None;

	/// <summary>
	/// Value indicating whether the column value is generated by the database when a row is inserted.
	/// </summary>
	public bool IsIdentity => databaseGenerated == DatabaseGeneratedOption.Identity;

	/// <summary>
	/// Value indicating whether the column value is nullable.
	/// </summary>
	public bool IsNullable => Nullable.GetUnderlyingType(Type) is not null || nullability.WriteState != NullabilityState.NotNull;

	/// <summary>
	/// The column name.
	/// </summary>
	public string Name { get; } = propertyInfo.GetCustomAttribute<ColumnAttribute>()?.Name ?? propertyInfo.Name;

	/// <summary>
	/// The type of the column value.
	/// </summary>
	public Type Type => propertyInfo.PropertyType;

	/// <summary>
	/// Value indicating how the database generates values for this column.
	/// </summary>
	private readonly DatabaseGeneratedOption databaseGenerated = propertyInfo.GetCustomAttribute<DatabaseGeneratedAttribute>()?.DatabaseGeneratedOption ?? DatabaseGeneratedOption.None;

	/// <summary>
	/// The nullability information for the underlying property.
	/// </summary>
	private readonly NullabilityInfo nullability = nullabilityContext.Create(propertyInfo);

	/// <summary>
	/// Sets the property value of a specified object.
	/// </summary>
	/// <param name="instance">The object whose property value will be set.</param>
	/// <param name="value">The new property value.</param>
	public void SetValue(object? instance, object? value) => propertyInfo.SetValue(instance, value);
}
