using namespace System.ComponentModel.DataAnnotations.Schema
using namespace System.Management.Automation
using namespace System.Reflection
using namespace System.Threading

<#
.SYNOPSIS
	Provides information about a database column.
#>
class DbColumnInfo {

	<#
	.SYNOPSIS
		The nullability context.
	#>
	hidden static [ThreadLocal[NullabilityInfoContext]] $NullabilityContext = [ThreadLocal[NullabilityInfoContext]]::new([Func[NullabilityInfoContext]] { [NullabilityInfoContext]::new() })

	<#
	.SYNOPSIS
		Value indicating whether the column can be read.
	#>
	[bool] $CanRead

	<#
	.SYNOPSIS
		Value indicating whether the column can be written to.
	#>
	[bool] $CanWrite

	<#
	.SYNOPSIS
		Value indicating whether the column value is generated by the database.
	#>
	[bool] $IsComputed

	<#
	.SYNOPSIS
		Value indicating whether the column value is generated by the database when a row is inserted.
	#>
	[bool] $IsIdentity

	<#
	.SYNOPSIS
		Value indicating whether the column value is nullable.
	#>
	[bool] $IsNullable

	<#
	.SYNOPSIS
		The column name.
	#>
	[string] $Name

	<#
	.SYNOPSIS
		The type of the column value.
	#>
	[Type] $Type

	<#
	.SYNOPSIS
		The property information providing the column metadata.
	#>
	hidden [PropertyInfo] $Property

	<#
	.SYNOPSIS
		Creates new column information.
	.PARAMETER Property
		The property information providing the column metadata.
	#>
	DbColumnInfo([PropertyInfo] $Property) {
		$databaseGeneratedOption = [Attribute]::GetCustomAttribute($Property, [DatabaseGeneratedAttribute])?.DatabaseGeneratedOption ?? [DatabaseGeneratedOption]::None

		$this.CanRead = $Property.CanRead
		$this.CanWrite = $Property.CanWrite
		$this.IsComputed = $databaseGeneratedOption -ne [DatabaseGeneratedOption]::None
		$this.IsIdentity = $databaseGeneratedOption -eq [DatabaseGeneratedOption]::Identity
		$this.Name = [Attribute]::GetCustomAttribute($Property, [ColumnAttribute])?.Name ?? $Property.Name
		$this.Property = $Property
		$this.Type = $Property.PropertyType

		$this.IsNullable = (-not [Attribute]::IsDefined($Property, [ValidateNotNullAttribute])) -and `
			(($null -ne [Nullable]::GetUnderlyingType($Property.PropertyType)) -or ([DbColumnInfo]::NullabilityContext.Value.Create($Property).WriteState -ne [NullabilityState]::NotNull))
	}

	<#
	.SYNOPSIS
		Gets the property value of a specified object.
	.PARAMETER Instance
		The object whose property value will be returned.
	.OUTPUTS
		The property value of the specified object.
	#>
	[object] GetValue([object] $Instance) {
		return $this.Property.GetValue($Instance)
	}

	<#
	.SYNOPSIS
		Sets the property value of a specified object.
	.PARAMETER Instance
		The object whose property value will be set.
	.PARAMETER Value
		The new property value.
	#>
	[void] SetValue([object] $Instance, [object] $Value) {
		$this.Property.SetValue($Instance, $Value)
	}
}
